### ISSUE TITLE
Suddenly does not work

### ISSUE THREAD

**Issue by petitspois** [mpeterson2/save-session#129]
atom Version 1.0.2 (1.0.2)
save-session 0.15.6

**package: **
1. docblockr
2. highlight-column   
3. highlight-selected 
4. itg-dark-syntax    
5. minimap            
6. open-in-browser    
7. save-session

'x' button will not save the windows, before this is possible

**Comment by phord** [comment]
It's not working for me on 1.0.2.  But I did not try it on any earlier version, so I don't know if this is new or if I am doing something wrong.

It does "work" if I exit with the close button (Linux) but I think that's actually because the buffers are saved in ~/.atom/storage/* during a graceful shutdown and atom core restores from there on startup.  If I use `$ killall -9 atom`  instead to simulate a reboot, for example, I see my unsaved changes in save-session/projects/.../project.json, but they do not get restored to my open buffers.
