### ISSUE TITLE
'save-session.dataSaveFolder' could not set the default

### ISSUE THREAD

**Issue by martinfinke** [mpeterson2/save-session#132]
Hello, this package doesn't work for me (Atom 1.0.2, OS X 10.10). On startup, the Console shows the following warning:

```
'save-session.dataSaveFolder' could not set the default. Attempted default: undefined; Schema: {"type":"string","description":"The folder in which to save project states"}
```

And it doesn't restore any open tabs. A quick search brought up [this issue](https://github.com/mpeterson2/save-session/issues/65), maybe it's related?

**Comment by mpeterson2** [comment]
That default is set programmatically since it is a file path on your system. The normal way of setting defaults doesn't work. The issue you linked is an issue about the new tab on startup, so it's probably not related.

Can you check to see if there is a value for `save-session.dataSaveFolder` in your config?

**Comment by martinfinke** [comment]
Yes, there is:

```
  "save-session":
    dataSaveFolder: "/Users/martin/.atom/projects"
```

The folder actually exists:
```
~ ls /Users/martin/.atom/projects/
./            ../           Users/        project.json
```

Below `Users`, there's a directory structure like my file system, and in some folders there is a `project.json` like this:

```
[{"path":"/Users/martin/Desktop/foo/bar/baz.cpp"},{"path":"/Users/martin/Desktop/foo/bar/test.h"}]
```

The open windows are saved in this file when I quit Atom. But they aren't loaded when I start Atom in that folder again.

**Comment by mpeterson2** [comment]
So Save Session doesn't actually reopen the windows anymore. This is something done by Atom core now. All Save Session does is save your unsaved file contents and restore those when Atom reopens its files.

It sounds like you are closing out of the window instead of the application, which causes Atom to remove that window from your last session. Using `cmd+q` or the quitting the app on the toolbar (`Atom`->`Quit Atom`) is how you should be exiting if you want to keep your last window in your session. If you are already doing this, perhaps it is a bug with Atom?

Let me know if this helps.

**Comment by martinfinke** [comment]
Oh ok thanks for clearing that up. I only need it to restore saved files. I ran in safe mode, re-enabled packages one by one and found that the [formatter-clang-format](https://atom.io/packages/formatter-clang-format) package was somehow breaking this functionality.

**Comment by mpeterson2** [comment]
Awesome. I'm glad you were able to figure it out.
