### ISSUE TITLE
Upgrading save-session package wipes old saved session?

### ISSUE THREAD

**Issue by victorhooi** [mpeterson2/save-session#48]
I've just upgraded save-session to the latest version (0.11.3), in order to fix the bug in #45 

However, when I start it back up, my last saved session is gone.

I wanted to check, is this by design?

If so, there should be a warning somewhere to users that upgrading the save-session package will blow away their saved session.

**Comment by mpeterson2** [comment]
It wasn't caused by the update, it was from the bug in issue #45. When the bug came up, it messed up your project file so that it couldn't be restored when you updated save session. Unfortunately, I don't believe there is anything you can do to get the project back at this time.

The best suggestion I've had so far was from #32, which suggests using git to keep snapshots to roll back to in case something like this happens.
